version: '3'

services:
    api:
        container_name: test_api
        build:
            context: .
            dockerfile: ./Dockerfile
        tty: true
        command: python /app/api/main.py
        restart: always
        volumes:
            - "./:/app"
        ports:
            - "8080:8080"